---

- name: "Tower Example"
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "NTP config"
      cisco.ios.ios_config:
        lines:
          - ntp server 99.99.99.99
      register: output
    
    - name: "Print"
      debug:
        msg: "{{ output }}"